sudo: false
language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm test
after_script:
  - if [[ `node --version` == *v0.12* ]]; then cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi  